services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb://mongo:27017/webmap  # Make sure to replace with your actual DB name
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - mongo
    command: sh -c "npm run initDatabase && npm run serve"

  frontend:
    build: ./frontend
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/usr/src/app

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
