services:
  backend:
    build: ./backend
    networks:
      - map_networks
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb+srv://${MONGO_DBUSER}:${MONGO_DBPASSWORD}@cluster0.xuonz.mongodb.net/web-map # Make sure to replace with your actual DB name
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - mongo
    command: sh -c "npm run initDatabase && npm run serve"

  frontend:
    build: ./frontend
    networks:
      - map_networks
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/usr/src/app

  mongo:
    networks:
      - map_networks
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

networks:
  map_networks:
    driver: bridge
